import {useEffect,useRef,useState} from 'react';
import {Compass,Notebook,Books,Sun,Moon,MagnifyingGlass,Plus,ArrowLeft,ArrowRight,ArrowSquareOut,CaretRight,Play,Pause,ArrowsOut,Stack,ArrowCounterClockwise,X,FloppyDisk,DownloadSimple,FileText,Atom,Drop,Cursor,LockSimple,Check,LinkSimple} from '@phosphor-icons/react';
import {createWorld,stops} from './model';
import localReportText from './report.md?raw';
import extracted from './references.json';
const reportText=import.meta.env.DEV?localReportText:'';
import {morphologySources} from './morphology-sources';
import {StudyPanel} from './StudyPanel';
import {ScreenComments,readComments} from './ScreenComments';
const types=['Nota','Pergunta','Insight','Hipótese','Observação de laboratório','Síntese'];
const levels=['Organismo','Rede','Tubo','Interior'];
const info=[
 {title:'Physarum polycephalum',eyebrow:'PLASMÓDIO · VISÃO GERAL',description:'Uma rede viva para explorar. Aproxime-se de um tubo e atravesse suas estruturas para estudar o organismo por dentro.'},
 {title:'Rede tubular',eyebrow:'ORGANIZAÇÃO · CONEXÕES',description:'Observe a malha, gire o organismo e selecione o tubo em destaque. Continue aproximando para alcançar sua superfície.'},
 {title:'Tubo plasmodial',eyebrow:'ESTRUTURA · SUPERFÍCIE',description:'Continue aproximando para entrar no trecho selecionado. Um corte didático dá acesso ao interior; a estrutura permanece conectada à rede.'},
 {title:'Interior do tubo plasmodial',eyebrow:'EXPLORAÇÃO · INTERIOR',description:'Você está dentro do tubo. Mude a direção do olhar, observe as estruturas e selecione um núcleo para abrir seu contexto de estudo.'}
];
const clean=s=>s.replace(/[^]*/g,'').replace(/\*\*/g,'').trim();
const report=import.meta.env.DEV?{id:'report',title:'Biologia e funcionamento do Physarum',kind:'Relatório de Deep Research',status:'Documento secundário',origin:'Arquivo fornecido por você'}:null;
function read(key){try{const v=JSON.parse(localStorage.getItem(key));return Array.isArray(v)?v:[];}catch{return [];}}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function IB({title,children,...props}){return <button className="icon-button" title={title} aria-label={title} {...props}>{children}</button>;}
function Modal({title,children,onClose,wide=false}){const ref=useRef();useEffect(()=>{const prev=document.activeElement;ref.current.showModal();return()=>prev?.focus();},[]);return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><header><h2>{title}</h2><IB title="Fechar" onClick={onClose}><X size={22}/></IB></header>{children}</dialog>;}
function NoteForm({context,initial,onSave,onClose}){const [kind,setKind]=useState(initial?.kind||'Nota'),[body,setBody]=useState(initial?.body||'');return <Modal title={initial?'Editar registro':'Registrar no caderno'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(body.trim())onSave({id:initial?.id||crypto.randomUUID(),kind,body:body.trim(),context:initial?.context||context,date:initial?.date||new Date().toISOString(),updated:new Date().toISOString()});}}><label>Tipo de entrada<select value={kind} onChange={e=>setKind(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>O que você está pensando?<textarea required autoFocus rows={7} value={body} onChange={e=>setBody(e.target.value)} placeholder="Uma leitura, uma conexão, uma pergunta…"/></label><p className="context-line"><LinkSimple size={16}/>Physarum / {initial?.context||context}</p><footer><span>Salvo neste navegador</span><button className="primary"><FloppyDisk size={18}/>Salvar registro</button></footer></form></Modal>;}
export function App(){
 const [controlsHidden,setControlsHidden]=useState(false),[commentFrozen,setCommentFrozen]=useState(false),[view,setView]=useState('Explorar'),[stage,setStage]=useState(0),[depth,setDepth]=useState(0),[selected,setSelected]=useState(''),[paused,setPaused]=useState(false),[isolated,setIsolated]=useState(false),[separated,setSeparated]=useState(false),[light,setLight]=useState(false),[error,setError]=useState('');
 const [notes,setNotes]=useState(()=>read('caderno-vivo.notes.v1')),[sources,setSources]=useState(()=>read('caderno-vivo.sources.v1')),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[noteModal,setNoteModal]=useState(false),[edit,setEdit]=useState(null),[reader,setReader]=useState(null),[sourceModal,setSourceModal]=useState(false),[notice,setNotice]=useState('');
 const host=useRef(),world=useRef(),timer=useRef(),detail=info[stage];
 const toast=m=>{setNotice(m);clearTimeout(timer.current);timer.current=setTimeout(()=>setNotice(''),3500);};
 useEffect(()=>{try{world.current=createWorld(host.current,{onStage:s=>{setStage(s);setSelected('');},onDepth:setDepth,onSelect:setSelected});}catch(e){setError('Não foi possível iniciar a cena 3D. Confira a aceleração gráfica do navegador.');console.error(e);}return()=>{world.current?.dispose();clearTimeout(timer.current);};},[]);
 useEffect(()=>{world.current?.pause(paused||commentFrozen||view!=='Explorar');},[paused,view,commentFrozen]);
 const go=p=>{world.current?.go(p);setSelected('');};
 const nav=v=>{setView(v);setQuery('');setFilter('Todos');};
 const newNote=()=>{setEdit(null);setNoteModal(true);};
 const saveNote=n=>{const next=notes.some(i=>i.id===n.id)?notes.map(i=>i.id===n.id?n:i):[n,...notes];try{localStorage.setItem('caderno-vivo.notes.v1',JSON.stringify(next));setNotes(next);setNoteModal(false);toast('Registro salvo no seu caderno.');}catch{toast('Não foi possível salvar. Confira o armazenamento do navegador.');}};
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),notes,sources,...(import.meta.env.DEV?{comments:readComments()}:{})},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`caderno-vivo-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const captureComment=()=>({view,depth,label:selected||detail.title,selected,query,filter,paused,isolated,separated,light,controlsHidden,camera:world.current?.snapshot(),scrolls:['.workspace-page','.panel-content'].map(selector=>({selector,top:document.querySelector(selector)?.scrollTop||0}))});
 const restoreComment=c=>{setControlsHidden(!!c.controlsHidden);setView(c.view);setQuery(c.query||'');setFilter(c.filter||'Todos');setPaused(c.paused);setIsolated(c.isolated);setSeparated(c.separated);setLight(c.light);setStage(c.camera?.stage??0);setSelected(c.selected||'');world.current?.restore(c.camera);world.current?.isolate(c.isolated);world.current?.separate(c.separated);world.current?.theme(c.light);requestAnimationFrame(()=>{for(const s of c.scrolls||[]){const el=document.querySelector(s.selector);if(el)el.scrollTop=s.top;}});};
 const visibleNotes=notes.filter(n=>(filter==='Todos'||n.kind===filter)&&normalize(`${n.body} ${n.context}`).includes(normalize(query)));
 const visibleSources=[...(report?[report]:[]),...morphologySources,...sources,...extracted].filter(s=>normalize(`${s.title} ${s.kind}`).includes(normalize(query)));
 const suggested=selected==='Núcleo'?extracted.filter(s=>/Tong|Schaap|Takano/.test(s.title)).slice(0,3):[...morphologySources,...(stage===3?extracted.filter(s=>/Tong/.test(s.title)).slice(0,1):[])];
 const structures=stage<2?[[Stack,'Rede tubular','Conexões e organização espacial'],[Drop,'Tubo plasmodial','Caminho para o interior'],[Stack,'Frente de expansão','Regiões em lâmina na borda']]:[[Drop,'Endoplasma','Fluxo ilustrativo no interior'],[Atom,'Núcleo','Selecione na cena ou aqui'],[Stack,'Córtex contrátil','Fibras periféricas esquemáticas']];
 return <div className={`app ${light?'light':''}`}>
 <header className="topbar"><div className="brand"><Atom size={28} weight="duotone"/><span>Caderno Vivo<span className="brand-detail"> / Physarum</span></span></div><div className="top-right">{import.meta.env.DEV&&<ScreenComments Modal={Modal} capture={captureComment} restore={restoreComment} onFreeze={setCommentFrozen} toast={toast}/>}<span className="privacy"><LockSimple size={13}/>Acervo local</span><IB title={light?'Ativar modo escuro':'Ativar modo claro'} onClick={()=>{setLight(!light);world.current?.theme(!light);}}>{light?<Moon size={20}/>:<Sun size={20}/>}</IB></div></header>
 <nav className="rail" aria-label="Navegação principal">{[[Compass,'Explorar'],[Notebook,'Caderno'],[Books,'Fontes']].map(([Icon,label])=><button key={label} className={view===label?'active':''} onClick={()=>nav(label)} aria-current={view===label?'page':undefined}><Icon size={27} weight={view===label?'duotone':'regular'}/><span>{label}</span></button>)}<button className="rail-bottom" onClick={exportData} title="Exportar caderno e fontes"><DownloadSimple size={24}/><span>Exportar</span></button></nav>
 <main className={`explorer ${view!=='Explorar'?'hidden':''}`}><section className={`viewport ${controlsHidden?'controls-hidden':''}`} aria-label="Exploração biológica"><div className="scene" ref={host}/>{error&&<div className="scene-message">{error}</div>}
 <button className="controls-toggle" aria-pressed={controlsHidden} onClick={()=>setControlsHidden(!controlsHidden)}>{controlsHidden?'Mostrar controles':'Ocultar controles'}</button>
 <div className="scene-top"><nav className="breadcrumbs" aria-label="Profundidade biológica">{levels.map((l,i)=><span key={l}>{i>0&&<CaretRight size={12}/>}<button className={stage===i?'current':''} onClick={()=>go(stops[i])}>{l}</button></span>)}</nav><IB title="Voltar uma escala" disabled={stage===0} onClick={()=>go(stops[Math.max(0,stage-1)])}><ArrowLeft size={20}/></IB></div>
 <div className="scene-title"><span className="eyebrow">{selected==='Frente de expansão'?'MORFOLOGIA · FRENTE':detail.eyebrow}</span><h1>{selected==='Frente de expansão'?'Frente de expansão':stage===0?<><em>Physarum</em><br/><em>polycephalum</em></>:stage===3?'Por dentro da rede.':detail.title}</h1>{(stage!==0||selected==='Frente de expansão')&&<p>{selected==='Frente de expansão'?'Arraste para observar. Percorra os leques pelo painel.':stage===3?'Aproxime. Observe. Conecte.':'Continue aproximando para entrar.'}</p>}</div><div className="model-note">Modelo esquemático · Escalas ilustrativas</div>
 <div className="scene-controls"><div className="camera-actions"><IB title="Restaurar visão" onClick={()=>{go(0);setIsolated(false);setSeparated(false);world.current?.isolate(false);world.current?.separate(false);}}><ArrowCounterClockwise size={20}/></IB><IB title="Isolar tubo" aria-pressed={isolated} onClick={()=>{setIsolated(!isolated);world.current?.isolate(!isolated);}}><ArrowsOut size={20}/></IB><IB title="Separar camadas" aria-pressed={separated} onClick={()=>{setSeparated(!separated);world.current?.separate(!separated);}}><Stack size={20}/></IB><IB title={paused?'Retomar fluxo':'Pausar fluxo'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={19}/>:<Pause size={19}/>}</IB></div><span className="flow-label">{paused?'Fluxo pausado':'Fluxo ilustrativo'}</span></div>
 <div className="depth-control"><div><span>SUPERFÍCIE</span><label htmlFor="depth">Profundidade <strong>{depth}%</strong></label><span>INTERIOR</span></div><input id="depth" aria-label="Profundidade da exploração" type="range" min="0" max="100" value={depth} onChange={e=>go(Number(e.target.value)/100)}/></div>
 <div className="scene-bottom"><span><Cursor size={20}/><span><strong>Role para atravessar as escalas</strong><small>Arraste para olhar. Clique para selecionar.</small></span></span><button className="enter-button" onClick={()=>go(selected==='Frente de expansão'?.22:stops[Math.min(stage+1,3)])} disabled={stage===3}>{selected==='Frente de expansão'?'Retomar percurso':stage===2?'Entrar no tubo':stage===3?'Você está no interior':'Aprofundar'}<ArrowRight size={17}/></button></div></section>
 <StudyPanel stage={stage} selected={selected} detail={detail} structures={structures} suggested={suggested} notes={notes} onFront={()=>world.current?.focusFront()} onNextFront={()=>world.current?.focusFront(1)} onBackToNetwork={()=>go(.22)} onSelect={name=>{setSelected(name);if(name==='Frente de expansão')world.current?.focusFront();if(name==='Tubo plasmodial'&&stage<2)go(.56);}} onReader={setReader} onNotebook={()=>nav('Caderno')} onNote={newNote} report={report}/></main>
 {view!=='Explorar'&&<main className="workspace-page"><div className="page-heading"><div><span className="eyebrow">PHYSARUM · ACERVO PESSOAL</span><h1>{view==='Caderno'?'Pensamentos em movimento.':'Uma biblioteca de conexões.'}</h1><p>{view==='Caderno'?'Guarde perguntas, observações e ideias. Retome cada uma no seu contexto.':'Suas referências e novos caminhos de leitura.'}</p></div><button className="primary" onClick={()=>view==='Caderno'?newNote():setSourceModal(true)}><Plus size={19}/>{view==='Caderno'?'Novo registro':'Adicionar fonte'}</button></div><div className="collection-tools"><label className="search"><MagnifyingGlass size={20}/><input aria-label="Buscar no acervo" placeholder={view==='Caderno'?'Buscar nos seus registros…':'Buscar títulos, assuntos ou tipos…'} value={query} onChange={e=>setQuery(e.target.value)}/></label><span>{view==='Caderno'?visibleNotes.length:visibleSources.length} {view==='Caderno'?'registros':'fontes'}</span></div>
 {view==='Caderno'?<><div className="filters">{['Todos',...types].map(t=><button className={filter===t?'active':''} key={t} onClick={()=>setFilter(t)}>{t}</button>)}</div>{visibleNotes.length===0?<div className="empty"><Notebook size={46} weight="thin"/><h2>{notes.length?'Nenhum registro encontrado':'O próximo insight começa aqui.'}</h2><p>{notes.length?'Tente outro termo ou tipo de entrada.':'Anote uma pergunta, uma leitura ou uma observação. Seu contexto de exploração acompanha o registro.'}</p><button className="secondary" onClick={newNote}>Criar um registro <Plus size={18}/></button></div>:<div className="notes-list">{visibleNotes.map(n=><button className="note-card" key={n.id} onClick={()=>{setEdit(n);setNoteModal(true);}}><div><span className="badge">{n.kind}</span><time>{new Date(n.updated||n.date).toLocaleDateString('pt-BR')}</time></div><p>{n.body}</p><footer><LinkSimple size={14}/>{n.context}<span>Editar <ArrowRight size={14}/></span></footer></button>)}</div>}<p className="storage-note"><LockSimple size={14}/>Registros salvos neste navegador. Use Exportar para manter uma cópia.</p></>:<><div className="source-origin"><FileText size={20}/><p><strong>Fontes com procedência.</strong> O acervo reúne referências do relatório, links pessoais e artigos consultados para o modelo. Cada entrada informa sua procedência e o que foi conferido.</p></div><div className="sources-list">{visibleSources.map(s=><button className="source-row" key={s.id} onClick={()=>setReader(s)}><div className="source-icon">{s.id==='report'?<Books size={28}/>:<FileText size={25}/>}</div><div><span className="eyebrow">{s.kind}</span><h3>{s.title.replace(/\*/g,'')}</h3><p>{s.origin}</p><span className="source-status">{s.status}</span></div><ArrowRight size={21}/></button>)}{!visibleSources.length&&<div className="empty"><h2>Nenhuma fonte encontrada.</h2><p>Tente outro termo de busca.</p></div>}</div></>}
 </main>}
 {noteModal&&<NoteForm context={selected||detail.title} initial={edit} onSave={saveNote} onClose={()=>setNoteModal(false)}/>}
 {reader&&<Modal title={reader.id==='report'?'Relatório-base':'Detalhes da fonte'} wide onClose={()=>setReader(null)}><div className="reader-meta"><span className="badge">{reader.status}</span><h2>{reader.title.replace(/\*/g,'')}</h2><p>Procedência: {reader.origin}</p>{reader.url&&<a className="primary" href={reader.url} target="_blank" rel="noreferrer">Abrir fonte original <ArrowSquareOut size={18}/></a>}<button className="secondary" onClick={()=>{setSelected(reader.title.replace(/\*/g,''));setReader(null);newNote();}}><Plus size={17}/>Anotar sobre esta leitura</button></div>{import.meta.env.DEV&&reader.id==='report'?<article className="report-text">{reportText.split('\n').map((line,i)=>{line=clean(line);if(!line)return null;return line.startsWith('#')?<h3 key={i}>{line.replace(/^#+\s*/,'')}</h3>:<p key={i}>{line}</p>;})}</article>:<div className="source-details"><h3>{reader.summaryLabel||'Trecho de origem'}</h3><p>{reader.excerpt||'Fonte adicionada manualmente ao acervo.'}</p><p className="muted">Esta entrada não significa que o conteúdo foi verificado. A conferência deve ser feita na fonte original.</p></div>}</Modal>}
 {sourceModal&&<Modal title="Adicionar fonte ao acervo" onClose={()=>setSourceModal(false)}><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget),url=data.get('url').trim();if(!/^https?:\/\//i.test(url)){toast('Use um endereço iniciado por https:// ou http://.');return;}const item={id:crypto.randomUUID(),title:data.get('title').trim(),url,kind:'Link',status:'Adicionada manualmente',origin:'Seu acervo'};try{const next=[item,...sources];localStorage.setItem('caderno-vivo.sources.v1',JSON.stringify(next));setSources(next);setSourceModal(false);toast('Fonte adicionada ao acervo.');}catch{toast('Não foi possível salvar esta fonte.');}}}><label>Título<input name="title" required placeholder="Título do artigo, vídeo ou documento"/></label><label>Endereço da fonte<input type="url" name="url" required placeholder="https://…"/></label><p className="muted">Nesta etapa, a entrada é manual por link. Importação de PDFs e catalogação assistida serão adicionadas posteriormente.</p><footer><span>Associada ao Physarum</span><button className="primary"><Plus size={18}/>Adicionar fonte</button></footer></form></Modal>}
 {notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 </div>;
}
