import {useEffect,useState} from 'react';
import {ChatCircleDots,X} from '@phosphor-icons/react';
export const commentsKey='caderno-vivo.comments.v1';
export function readComments(){try{const value=JSON.parse(localStorage.getItem(commentsKey));return Array.isArray(value)?value:[];}catch{return [];}}
export function ScreenComments({Modal,capture,restore,onFreeze,toast}){
 const [items,setItems]=useState(readComments),[open,setOpen]=useState(false),[marking,setMarking]=useState(false),[draft,setDraft]=useState(null),[body,setBody]=useState(''),[pin,setPin]=useState(null);
 useEffect(()=>{onFreeze(marking||!!draft||!!pin);return()=>onFreeze(false);},[marking,draft,pin]);
 useEffect(()=>{const escape=e=>{if(e.key==='Escape'){setMarking(false);setPin(null);}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 const save=next=>{try{localStorage.setItem(commentsKey,JSON.stringify(next));setItems(next);return true;}catch{toast('Não foi possível salvar os comentários. Confira o armazenamento.');return false;}};
 const copy=async()=>{const text=items.map((c,i)=>`${i+1}. [${c.done?'Resolvido':'Pendente'}] ${c.context.view} / ${c.context.label} / profundidade ${c.context.depth}%\nPonto: ${Math.round(c.point.x*100)}% da largura, ${Math.round(c.point.y*100)}% da altura; tela ${c.point.width} × ${c.point.height}.\n${c.body}`).join('\n\n');try{await navigator.clipboard.writeText('Ajustes no Caderno Vivo:\n\n'+text);toast('Comentários copiados. Cole aqui na conversa para pedir os ajustes.');}catch{toast('Não foi possível copiar. Use Exportar comentários.');}};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,comments:items},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='caderno-vivo-comentarios.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <>
 <button className="comment-trigger" onClick={()=>{setPin(null);setOpen(true);}}><ChatCircleDots size={19}/>Comentar tela{items.filter(c=>!c.done).length>0&&<span>{items.filter(c=>!c.done).length}</span>}</button>
 {open&&<Modal title="Comentários da tela" onClose={()=>setOpen(false)}><div className="comments-content"><p className="muted">Marque um ponto e descreva o ajuste. Os comentários ficam neste navegador, separados das notas de estudo.</p><button className="primary" onClick={()=>{setOpen(false);setMarking(true);}}>Marcar um ponto na tela</button><div className="comment-list">{!items.length&&<p className="muted">Ainda não há comentários. Navegue até o que deseja ajustar e marque um ponto.</p>}{items.map((c,i)=><article className="comment-card" key={c.id}><strong>{i+1}. {c.context.view} · {c.context.depth}%</strong><small>{c.context.label}</small><p>{c.body}</p><div><button className="secondary" onClick={()=>{restore(c.context);setOpen(false);setPin({...c,number:i+1});}}>Ver ponto</button><label><input type="checkbox" checked={!!c.done} onChange={()=>save(items.map(item=>item.id===c.id?{...item,done:!item.done}:item))}/>Resolvido</label></div></article>)}</div><footer><button className="secondary" disabled={!items.length} onClick={copy}>Copiar para a conversa</button><button className="secondary" disabled={!items.length} onClick={download}>Exportar comentários</button></footer><p className="muted">Depois de copiar, cole na conversa comigo. Não há envio automático. O ponto é uma marcação da tela, não uma âncora na geometria 3D.</p></div></Modal>}
 {marking&&<div className="comment-capture" role="button" tabIndex={0} aria-label="Escolher ponto para comentário" onKeyDown={e=>{if(e.key==='Enter'){setDraft({point:{x:.5,y:.5,width:innerWidth,height:innerHeight},context:capture()});setBody('');setMarking(false);}}} onClick={e=>{setDraft({point:{x:e.clientX/innerWidth,y:e.clientY/innerHeight,width:innerWidth,height:innerHeight},context:capture()});setBody('');setMarking(false);}}><div className="comment-hint">Clique onde deseja comentar · Esc para cancelar<button aria-label="Cancelar marcação" onClick={e=>{e.stopPropagation();setMarking(false);}}><X size={18}/></button></div></div>}
 {draft&&<Modal title="Comentar este ponto" onClose={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();if(!body.trim())return;if(save([...items,{...draft,id:crypto.randomUUID(),body:body.trim(),date:new Date().toISOString(),done:false}])){setDraft(null);setOpen(true);toast('Comentário salvo neste navegador.');}}}><p className="context-line">{draft.context.view} / {draft.context.label} · {draft.context.depth}%</p><label>O que deseja ajustar?<textarea autoFocus required rows={5} value={body} onChange={e=>setBody(e.target.value)} placeholder="Descreva o que mudar e como gostaria que ficasse…"/></label><footer><button type="button" className="secondary" onClick={()=>setDraft(null)}>Cancelar</button><button className="primary">Salvar comentário</button></footer></form></Modal>}
 {pin&&<div className="comment-pin-layer"><span className="comment-pin" style={{left:`${pin.point.x*100}%`,top:`${pin.point.y*100}%`}}>{pin.number}</span><div className="comment-hint"><span>{pin.body}<small>Posição de tela aproximada se a janela mudou de tamanho.</small></span><button className="secondary" onClick={()=>{setPin(null);setOpen(true);}}>Voltar aos comentários</button></div></div>}
 </>;
}
