const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1488,height:1058},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle',timeout:120000});
 await page.locator('canvas').waitFor();
 await page.waitForTimeout(2000);
 fs.mkdirSync('qa',{recursive:true});
 await page.screenshot({path:'qa/organismo.png'});
 await page.getByRole('button',{name:'Tubo plasmodial Caminho para o interior',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#depth').value==='56');
 await page.getByRole('button',{name:'Alim et al. · 2013 Rede tubular e contrações'}).click();
 if(!(await page.locator('dialog').innerText()).includes('Consulta parcial ao original'))throw Error('Morphology provenance missing');
 await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Interior',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#depth').value==='88');
 await page.screenshot({path:'qa/interior.png'});
 await page.mouse.click(400,600);
 const structure=await page.locator('.study-panel h2').innerText();
 if(!['Núcleo','Tubo plasmodial'].includes(structure))throw Error('3D structure selection failed');
 await page.getByRole('button',{name:'Registrar uma ideia',exact:true}).click();
 await page.getByLabel('Tipo de entrada').selectOption('Pergunta');
 await page.getByLabel('O que você está pensando?').fill('TESTE AUTOMATIZADO: relação entre fluxo e transporte nuclear?');
 await page.getByRole('button',{name:'Salvar registro',exact:true}).click();
 await page.getByRole('button',{name:'Caderno',exact:true}).click();
 await page.getByLabel('Buscar no acervo').fill('transporte nuclear');
 if(await page.locator('.note-card').count()!==1)throw Error('Note/search failed');
 await page.reload({waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Caderno',exact:true}).click();
 if(await page.locator('.note-card').count()!==1)throw Error('Persistence failed');
 await page.getByRole('button',{name:'Insight',exact:true}).click();
 if(await page.locator('.note-card').count()!==0)throw Error('Type filter failed');
 await page.getByRole('button',{name:'Todos',exact:true}).click();
 await page.screenshot({path:'qa/caderno.png'});
 await page.getByRole('button',{name:'Fontes',exact:true}).click();
 await page.getByRole('button',{name:'Adicionar fonte',exact:true}).click();
 await page.getByLabel('Título',{exact:true}).fill('Fonte de teste local');
 await page.getByLabel('Endereço da fonte').fill('https://example.org/research');
 await page.locator('dialog').getByRole('button',{name:'Adicionar fonte',exact:true}).click();
 await page.getByLabel('Buscar no acervo').fill('Fonte de teste local');
 if(await page.locator('.source-row').count()!==1)throw Error('Source import/search failed');
 await page.getByLabel('Buscar no acervo').fill('');
 const sourceCount=await page.locator('.source-row').count();
 await page.screenshot({path:'qa/fontes.png'});
 await page.getByRole('button',{name:'Ativar modo claro',exact:true}).click();
 await page.screenshot({path:'qa/claro.png'});
 await page.getByRole('button',{name:'Explorar',exact:true}).click();
 await page.getByRole('button',{name:'Ativar modo escuro',exact:true}).click();
 await page.getByRole('button',{name:'Ler relatório-base',exact:true}).click();
 if(!(await page.locator('.report-text').innerText()).includes('Physarum'))throw Error('Report missing');
 await page.getByRole('button',{name:'Fechar',exact:true}).click();
 await page.getByRole('button',{name:'Interior',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#depth').value==='88');
 await page.getByRole('button',{name:'Pausar fluxo',exact:true}).click();
 await page.getByRole('button',{name:'Separar camadas',exact:true}).click();
 await page.getByRole('button',{name:'Voltar uma escala',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#depth').value==='56');
 await page.getByRole('button',{name:'Restaurar visão',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#depth').value==='0');
 await page.mouse.move(600,550);await page.mouse.wheel(0,100);
 await page.waitForFunction(()=>Number(document.querySelector('#depth').value)>0);
 await page.setViewportSize({width:1024,height:768});
 await page.screenshot({path:'qa/desktop-compacto.png'});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw Error('Horizontal overflow');
 fs.writeFileSync('qa/result.json',JSON.stringify({errors,checks:['3D canvas','continuous-depth navigation','wheel zoom','integrated tube marker','3D structure selection','morphology source provenance','note creation','note persistence','text search','type filters','manual source addition','report reader','light/dark','pause','layer separation','back navigation','reset','1024px layout'],sourceCount},null,2));
 console.log(JSON.stringify({errors,result:errors.length?'failed':'passed'}));
 await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1);});
